# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0csensor.proto\"\x8f\x01\n\rSensorReading\x12\x10\n\x08location\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\x12*\n\x06values\x18\x03 \x03(\x0b\x32\x1a.SensorReading.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENSORREADING_VALUESENTRY = _descriptor.Descriptor(
  name='ValuesEntry',
  full_name='SensorReading.ValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='SensorReading.ValuesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='SensorReading.ValuesEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=160,
)

_SENSORREADING = _descriptor.Descriptor(
  name='SensorReading',
  full_name='SensorReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='SensorReading.location', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SensorReading.timestamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='SensorReading.values', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SENSORREADING_VALUESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=160,
)

_SENSORREADING_VALUESENTRY.containing_type = _SENSORREADING
_SENSORREADING.fields_by_name['values'].message_type = _SENSORREADING_VALUESENTRY
DESCRIPTOR.message_types_by_name['SensorReading'] = _SENSORREADING

SensorReading = _reflection.GeneratedProtocolMessageType('SensorReading', (_message.Message,), dict(

  ValuesEntry = _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), dict(
    DESCRIPTOR = _SENSORREADING_VALUESENTRY,
    __module__ = 'sensor_pb2'
    # @@protoc_insertion_point(class_scope:SensorReading.ValuesEntry)
    ))
  ,
  DESCRIPTOR = _SENSORREADING,
  __module__ = 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:SensorReading)
  ))
_sym_db.RegisterMessage(SensorReading)
_sym_db.RegisterMessage(SensorReading.ValuesEntry)


_SENSORREADING_VALUESENTRY.has_options = True
_SENSORREADING_VALUESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
